"use client";

import Button from "@mui/joy/Button";
import FileDownloadIcon from "@mui/icons-material/FileDownload";

import { Fragment, useEffect, useState } from "react";
import { getURL } from "../../utils";

import dayjs from "dayjs";
import { useSnackbar } from "notistack";
import usePermissionContext from "../../Home/permissionContext/usePermission";

function ExportEspera() {
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    return mounted ? <Export /> : null;
}

function Export() {
    const { enqueueSnackbar } = useSnackbar();
    const { isLoading: permissionIsLoading, hasPermission } =
        usePermissionContext();

    const [loading, setLoading] = useState(false);

    const onClick = () => {
        setLoading(true);
        fetch(getURL("/api/usuarios/espera/exportar"), {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
        })
            .then(async (response) => {
                if (!response.ok) {
                    enqueueSnackbar(
                        `No se pudo exportar el archivo. (${String(
                            response?.statusText ?? response,
                        )})`,
                        { variant: "error" },
                    );
                } else {
                    // Generated by Copilot
                    const blob = await response.blob();
                    const contentDisposition = response.headers.get(
                        "Content-Disposition",
                    );
                    let filename = `Lista de espera_${dayjs().format(
                        "YYYY-MM-DD HH-mm-ss",
                    )}.xlsx`;

                    if (contentDisposition) {
                        const match = contentDisposition.match(/filename=(.+)/);
                        if (match.length === 2) {
                            filename = match[1];
                        }
                    }

                    const reader = new FileReader();
                    reader.onload = () => {
                        const link = document.createElement("a");
                        link.href = reader.result;
                        link.download = filename;
                        link.click();
                    };
                    reader.readAsDataURL(blob);
                    enqueueSnackbar("Archivo exportado correctamente.", { variant: "success" });
                }
            })
            .catch((error) => {
                enqueueSnackbar(
                    `No se pudo exportar el archivo. (${String(
                        error?.statusText ?? error ?? "UNKNOWN_ERROR",
                    )})`,
                    { variant: "error" },
                );
            })
            .finally(() => {
                setLoading(false);
            });
    };

    return (
        <Fragment>
            {permissionIsLoading ? null : hasPermission(
                  "autenticacion.exportar_lista_espera",
              ) ? (
                <Button
                    startDecorator={<FileDownloadIcon />}
                    disabled={loading}
                    loading={loading}
                    onClick={onClick}
                    variant="solid"
                    color="primary"
                    sx={{
                        maxWidth: { md: "250px" },
                    }}
                >
                    Exportar lista de espera
                </Button>
            ) : null}
        </Fragment>
    );
}

export default ExportEspera;
