"use client";

import Button from "@mui/joy/Button";
import ButtonGroup from "@mui/joy/ButtonGroup";
import IconButton from "@mui/joy/IconButton";
import Menu from "@mui/joy/Menu";
import MenuItem from "@mui/joy/MenuItem";

import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import FileDownloadIcon from "@mui/icons-material/FileDownload";

import { Fragment, useRef, useState } from "react";
import { getURL } from "../utils";

import { useCiclo } from "@/contexts/CicloContext";
import { useIsClient, useLocalStorage } from "@uidotdev/usehooks";
import dayjs from "dayjs";
import { useSnackbar } from "notistack";
import useSWR from "swr";
import usePermissionContext from "../Home/permissionContext/usePermission";

const options = [
    {
        label: "Exportar todos los inscritos",
    },
];

function ExportUsers() {
    const mounted = useIsClient();

    return mounted ? <Export /> : null;
}

function Export() {
    const { enqueueSnackbar } = useSnackbar();
    const { isLoading: permissionIsLoading, hasPermission } =
        usePermissionContext();

    const [loading, setLoading] = useState(false);
    const [open, setOpen] = useState(false);
    const actionRef = useRef(null);
    const [anchorEl, setAnchorEl] = useState(null);
    const [selectedIndex, setSelectedIndex] = useLocalStorage(
        "ExportUsers__selectedIndex",
        0
    );

    const { selectedCicloId } = useCiclo();
    const { data: cursos, isLoading } = useSWR(
        selectedCicloId
            ? getURL(
                  `api/usuarios/cursos/disponibles?ciclo_id=${selectedCicloId}`
              )
            : null
    );

    const onClick = () => {
        setLoading(true);
        
        // Construir la URL base
        let url = "/api/usuarios/exportar/inscritos";
        
        // Si selectedIndex > 0, es un curso específico
        if (selectedIndex > 0 && cursos && cursos.length > 0) {
            const cursoIndex = selectedIndex - 1;
            if (cursos[cursoIndex]) {
                url += `/${cursos[cursoIndex].id}`;
            }
        }
        
        fetch(
            getURL(url),
            {
                method: "GET",
                headers: {
                    "Content-Type": "application/json",
                },
            }
        )
            .then(async (response) => {
                if (!response.ok) {
                    enqueueSnackbar(
                        `No se pudo exportar el archivo. (${String(
                            response?.statusText ?? response
                        )})`,
                        { variant: "error" }
                    );
                } else {
                    // Generated by Copilot
                    const blob = await response.blob();
                    const contentDisposition = response.headers.get(
                        "Content-Disposition"
                    );
                    let filename = `Personas inscritas_${dayjs().format(
                        "YYYY-MM-DD HH-mm-ss"
                    )}.xlsx`;

                    if (contentDisposition) {
                        const match = contentDisposition.match(/filename=(.+)/);
                        if (match.length === 2) {
                            filename = match[1];
                        }
                    }

                    const reader = new FileReader();
                    reader.onload = () => {
                        const link = document.createElement("a");
                        link.href = reader.result;
                        link.download = filename;
                        link.click();
                    };
                    reader.readAsDataURL(blob);
                    enqueueSnackbar("Archivo exportado correctamente.", { variant: "success" });
                }
            })
            .catch((error) => {
                enqueueSnackbar(
                    `No se pudo exportar el archivo. (${String(
                        error?.statusText ?? error ?? "UNKNOWN_ERROR"
                    )})`,
                    { variant: "error" }
                );
            })
            .finally(() => {
                setLoading(false);
            });
    };

    const handleMenuItemClick = (event, index) => {
        setSelectedIndex(index);
        setOpen(false);
    };

    return (
        <Fragment>
            {permissionIsLoading ? null : hasPermission(
                  "autenticacion.exportar_inscritos"
              ) ? (
                <Fragment>
                    <ButtonGroup
                        ref={setAnchorEl}
                        variant="solid"
                        color="primary"
                        aria-label="split button"
                        sx={{
                            width: { md: "325px" },
                            maxWidth: { md: "325px" },
                        }}
                    >
                        <Button
                            startDecorator={<FileDownloadIcon />}
                            disabled={loading}
                            loading={loading}
                            onClick={onClick}
                            sx={{
                                width: { md: "289px" },
                                height: { md: "36px" },
                                "& span": {
                                    textWrap: { md: "nowrap" },
                                    textOverflow: { md: "ellipsis" },
                                    overflow: { md: "hidden" },
                                },
                            }}
                        >
                            <span>
                                {options[selectedIndex]?.label ??
                                    `Exportar "${
                                        cursos?.at(selectedIndex - 1)
                                            ?.shortname ||
                                        cursos?.at(selectedIndex - 1)?.name
                                    }"`}
                            </span>
                        </Button>
                        <IconButton
                            aria-controls={
                                open ? "split-button-menu" : undefined
                            }
                            aria-expanded={open ? "true" : undefined}
                            aria-label="select merge strategy"
                            aria-haspopup="menu"
                            onMouseDown={() => {
                                actionRef.current = () => setOpen(!open);
                            }}
                            onKeyDown={() => {
                                actionRef.current = () => setOpen(!open);
                            }}
                            onClick={() => {
                                actionRef.current?.();
                            }}
                            disabled={loading}
                            // loading={loading}
                        >
                            <ArrowDropDownIcon />
                        </IconButton>
                    </ButtonGroup>
                    <Menu
                        open={open}
                        onClose={() => setOpen(false)}
                        anchorEl={anchorEl}
                    >
                        {options.map((option, index) => (
                            <MenuItem
                                key={index}
                                selected={index === selectedIndex}
                                onClick={(event) =>
                                    handleMenuItemClick(event, index)
                                }
                            >
                                {option.label}
                            </MenuItem>
                        ))}
                        {cursos?.map((curso, index) => (
                            <MenuItem
                                key={curso.id}
                                onClick={(event) =>
                                    handleMenuItemClick(event, index + 1)
                                }
                            >
                                Exportar inscritos en &quot;
                                {curso.shortname || curso.name}&quot;
                            </MenuItem>
                        ))}
                    </Menu>
                </Fragment>
            ) : null}
        </Fragment>
    );
}

export default ExportUsers;
